Functional/README.md
L1/README.md
Platform/README.md

cleanup
Signed-off-by: Mircea Dan Gheorghe <mircea-dan.gheorghe@keysight.com>

removed empty folders

---

docs/How_to_install_dentOS.md

Add How_to_Install_dentOS_Instrutions

Add How_to_Install_dentOS_Instrutions

---

DentOS_Framework/DentOsTestbed/README.md
DentOS_Framework/DentOsTestbed/configuration/README.md
DentOS_Framework/DentOsTestbedLib/README.md
DentOS_Framework/README.md
README.md
docs/Feature_test_bed/README.md
docs/How_to_install_dentOS.md
docs/How_to_start_and_run_testcases.md
docs/README.md
docs/System_integration_test_bed/README.md

this PR is addressing some md file formatting and spelling errors it must go in before the pr enabling ci workflow for spelling errors
Signed-off-by: mgheorghe <mircea-dan.gheorghe@keysight.com>

spelling errors fixes

---

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/test_utils/tb_utils.py

Signed-off-by: Anton Putria <anton.putrya@plvision.eu>

Added testbed util function for running tcpdump on device.

---

.wordlist.txt
README.md

- spellcheck
- linters
- python

CI badges on main page

---

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/basic_triggers/test_module1.py

Signed-off-by: Chetan Murthy <muchetan@amazon.com>

Fix for checking default Route

---

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/constants.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv4/test_ipv4_addr.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv4/test_ipv4_class_x_discarded.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv4/test_ipv4_en_dis_fwd.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv4/test_ipv4_routing.py

This includes:
- test_ipv4_addr
- test_ipv4_class_a_dis
- test_ipv4_class_b_dis
- test_ipv4_class_c_dis
- test_ipv4_class_d_dis
- test_ipv4_class_e_dis
- test_ipv4_en_dis_fwd
- test_ipv4_random_routing
- test_ipv4_nexthop_route
- test_ipv4_route_between_vlan_devs
**This PR depends on** https://github.com/dentproject/testing/pull/88, https://github.com/dentproject/testing/pull/89, https://github.com/dentproject/testing/pull/90

Add IPv4 tests

---

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/constants.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_admin_state_down_up.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_fdb_flush_on_down.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_learning_address.py

This includes:
- test_bridging_admin_state_down_up
- test_bridging_fdb_flush_on_down
- test_bridging_learning_address
Signed-off-by: Kostiantyn Stavruk <kostiantyn.stavruk@plvision.eu>

Add Bridging tests

---

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/constants.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/vlan/test_vlan_all_supported_modes.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/vlan/test_vlan_untagged_ports.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/test_utils/br_utils.py

Test added:
```
test_untagged_broadcast
test_untagged_multicast
test_untagged_unicast
```
Signed-off-by: Stepan Vovk [stepan.vovk@plvision.eu](mailto:stepan.vovk@plvision.eu)

Add VLAN untagged ports tests

---

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/constants.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/vlan/test_vlan_configuration_checks.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/bridge/linux/linux_bridge_vlan_impl.py

Added 2 tests:
`test_can_not_add_interface_to_vlan_wo_bridge`,
`test_can_set_max_vlans`
Signed-off-by: Stepan Vovk <stepan.vovk@plvision.eu>

VLAN configuration tests

---

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv4/test_ipv4_icmp.py

- test_ipv4_icmp_disabled
- test_ipv4_ping_stability
- test_ipv4_ping_size
- test_ipv4_ping_static_ip
- test_ipv4_fwd_disable

Add IPv4 icmp tests

---

DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/ixnetwork/ixnetwork_ixia_client_impl.py

Adds VLAN priority to packet stream creation
Adds tracking by VLAN id, priority if VLAN in stream
Signed-off-by: Stepan Vovk <stepan.vovk@plvision.eu>

Add  tracking by VLAN id, priority

---

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv4/test_ipv4_arp.py

- test_ipv4_replace_dyn_stat_arp
- test_ipv4_arp_reachable_timeout
- test_ipv4_arp_ageing
- test_ipv4_dynamic_arp.py
- test_ipv4_static_arp.py
- test_ipv4_static_arp_with_traffic.py
- test_ipv4_static_route_over_static_arp.py

Add IPv4 arp tests

---

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv4/test_ipv4_routing.py

- test_ipv4_nexthop_static_route
- test_ipv4_two_routes_to_same_net

Add IPv4 routing tests

---

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv4/conftest.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv4/test_ipv4_gw.py

- test_ipv4_default_gw
- test_ipv4_not_connected_gw

Add IPv4 gateway tests

---

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv4/test_ipv4_best_match.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv4/test_ipv4_crc.py

- test_ipv4_bm_traffic_forwarding
- test_ipv4_checksum

Add IPv4 best match and crc tests

---

DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/ethtool/linux/linux_ethtool_impl.py

Added support for:
- -i - query driver
- -S - statistics
- -a - pause frames
- -k - offload features
- -P - read MAC
- duplex - set duplex mode
- advertise - set advertise value

Add ethtool options support

---

DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/bridge/linux/linux_bridge_fdb_impl.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/ip/linux/linux_ip_link_impl.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/ixnetwork/ixnetwork_ixia_client_impl.py

**Update linux_ip_link_impl.py, ixnetwork_ixia_client_impl.py and linux_bridge_fdb_imply.py**
- Added missing parametr: type, device.
- Added bad_crc options to set_ethernet_traffic function.

Update linux_ip_link_impl, ixnetwork_ixia_client_impl and linux_bridge_fdb_imply

---

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/vlan/test_vlan_all_supported_modes.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/vlan/test_vlan_configuration_checks.py

- Add clean up fixture to some tests
- update rate for multicast packet

VLAN fixes

---

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_full_fdb_traffic.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_learning_address_rate.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_relearning_on_different_vlans.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_robustness_macs.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_unregistered_traffic.py

**This includes:**
- test_bridging_relearning_on_different_vlans
- test_bridging_learning_address_rate
- test_bridging_unregistered_traffic
- test_bridging_robustness_macs
- test_bridging_full_fdb_traffic

add 5 bridging tests

---

DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/bridge/linux/linux_bridge_vlan_impl.py

Fix setting VLAN pvid  on port.

Fix vlan pvid set

---

DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/ixnetwork/ixnetwork_ixia_client_impl.py

Adds support for setting different frame rate types

Add frame rate support

---

DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/ixnetwork/ixnetwork_ixia_client_impl.py

Add packet TTL option

---

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/conftest.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/test_utils/cleanup_utils.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/os/linux/linux_sysctl_impl.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/os/recoverable_sysctl.py

Added a possibility to use RecoverableSysctl API that resets changed values to its initial state after the test.

Add recoverable sysctl and cleanup function

---

DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/ixnetwork/ixnetwork_ixia_client_impl.py

Adds dynamic support for current 2 IXIA cards in use:
- NovusTenGigLan
- Ethernet

Ethernet card support

---

DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/ixnetwork/ixnetwork_ixia_client_impl.py

Added ability to change transmission control mode on traffic items.
Added 2 new modes:
- fixedFrameCount
- fixedDuration
Resolves: #225

Added ability to change transmission control mode

---

DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/ixnetwork/ixnetwork_ixia_client_impl.py

Updated `ixnetwork_ixia_client_impl.py` and added ability to send IGMP traffic of different versions (v1-v3).
Also added ability to set `totalLength` for ipv4 packet. 
Resolves: #143

Add Igmp traffic and totalLength

---

.github/configs/.wordlist.txt
.pre-commit-config.yaml
docs/Code_commit_process/README.md

pre-commit check to improve code quality.
fixes https://github.com/dentproject/testing/issues/177

pre-commit check

---

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/test_utils/tgen_utils.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/ixnetwork/ixnetwork_ixia_client_impl.py

Added ability to delete specific traffic items by name using `tgen_utils_clear_traffic_items`.
Resolves: #207

Add ability to delete traffic item by name

---

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/vlan/test_vlan_default_configuration.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/vlan/test_vlan_switching_modes.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/vlan/test_vlan_tagged_ports.py

Adds following tests
```
- test_vlan_basic_functionality
- test_vlan_changing_default_pvid
- test_vlan_default_configuration_with_["broadcast", "multicast", "unicast", "unknown_unicast"]
- test_vlan_switching_vlan_modes_via_cli
- test_vlan_tagged_ports_with_["broadcast", "multicast", "unicast"]
```

Add vlan tests

---

.github/configs/.wordlist.txt
DentOS_Framework/Dockerfile
DentOS_Framework/Dockerfile.testing
DentOS_Framework/run.sh
docs/How_to_start_and_run_testcases.md

- Update docker environment to use the latest DentOS framework code on each run
- Add run.sh script to simplify environment setup
- Update run tests howto

Update run tests howto and docker environment

---

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/constants.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv6/conftest.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv6/ipv6_utils.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv6/test_ipv6.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv6/test_ipv6_bridge.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/ixnetwork/ixnetwork_ixia_client_impl.py

- test_ipv6_basic_config
- test_ipv6_move_host_on_bridge
- test_ipv6_on_bridge
- test_ipv6_on_bridge_vlan

Add IPv6 basic config and bridge tests 

---

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/test_utils/tgen_utils.py
DentOS_Framework/DentOsTestbedLib/gen/model/dent/traffic/traffic.yaml
DentOS_Framework/DentOsTestbedLib/gen/model/traffic/ixia/ixia.yaml
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/ixnetwork/ixnetwork_ixia_client.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/ixnetwork/ixnetwork_ixia_client_impl.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/traffic_gen.py

Add API to switch minFrameSize option on Ixia

---

.pre-commit-config.yaml
DentOS_Framework/DentOsTestbedLib/test/utils.py

auto check  python using flake 8
fix 3 very long line lengths
ignore all flake8 failures, to be fixed on by one in subsequent PRs
Signed-off-by: Mircea Dan <mircea-dan.gheorghe@keysight.com>

enable flake8 checks

---

.pre-commit-config.yaml
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/basic_triggers/test_module1.py
DentOS_Framework/DentOsTestbedLib/gen/code_generate.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/discovery/modules/mod_cpu_usage.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/discovery/modules/mod_disk_free.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/discovery/modules/mod_ip_address.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/discovery/modules/mod_ip_link.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/discovery/modules/mod_ip_route.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/discovery/modules/mod_lldp.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/discovery/modules/mod_memory_usage.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/discovery/modules/mod_onlp_sfp_info.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/discovery/modules/mod_onlp_system_info.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/discovery/modules/mod_poectl.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/discovery/modules/mod_process.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/discovery/modules/mod_service.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/poe_tester/dni/dni_poe_tester.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/ixnetwork/ixnetwork_ixia_client.py

python -m autopep8 --recursive --in-place --select E211 ./

E211 whitespace before '('

---

.pre-commit-config.yaml
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_forward_block_different_packets.py
DentOS_Framework/DentOsTestbedLib/test/test_dent_dcb_app.py
DentOS_Framework/DentOsTestbedLib/test/test_dent_devlink_port.py
DentOS_Framework/DentOsTestbedLib/test/test_dent_sysctl.py

python -m autopep8 --recursive --in-place --select E131 ./

E131 continuation line unaligned for hanging indent

---

.pre-commit-config.yaml
DentOS_Framework/DentOsTestbedLib/test/test_dent_dcb_app.py
DentOS_Framework/DentOsTestbedLib/test/test_dent_devlink_port.py
DentOS_Framework/DentOsTestbedLib/test/test_dent_sysctl.py

python -m autopep8 --recursive --in-place --select E251 ./

E251 unexpected spaces around keyword / parameter equals

---

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/L1/test_l1_autodetect.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/L1/test_l1_autoneg.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/L1/test_l1_forced_speed.py

Depends on [PR](https://github.com/dentproject/testing/pull/211)

Add L1 traffic tests

---

.pre-commit-config.yaml
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/utils/perf_util.py

package time clash with variable name, changed the variable name to something else.

F402 import 'time' from line 10 shadowed by loop variable

---

.pre-commit-config.yaml
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/ip/linux/linux_ip_route_impl.py

F524 '...'.format(...) is missing argument(s) for placeholder(s): 1

---

.pre-commit-config.yaml
DentOS_Framework/DentOsTestbedDiscovery/src/dent_os_testbed/discovery/LocalRepository.py
DentOS_Framework/DentOsTestbedDiscovery/src/dent_os_testbed/discovery/Module.py
DentOS_Framework/DentOsTestbedDiscovery/src/dent_os_testbed/discovery/Report.py
DentOS_Framework/DentOsTestbedLib/gen/lib/database.py
DentOS_Framework/DentOsTestbedLib/gen/lib/python/pylib.py
DentOS_Framework/DentOsTestbedLib/gen/plugins/discovery/plugin.py
DentOS_Framework/DentOsTestbedLib/gen/plugins/doc/plugin.py
DentOS_Framework/DentOsTestbedLib/gen/plugins/test/plugin.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/discovery/modules/mod_cpu_usage.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/discovery/modules/mod_disk_free.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/discovery/modules/mod_ip_address.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/discovery/modules/mod_ip_link.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/discovery/modules/mod_ip_route.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/discovery/modules/mod_lldp.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/discovery/modules/mod_memory_usage.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/discovery/modules/mod_onlp_sfp_info.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/discovery/modules/mod_onlp_system_info.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/discovery/modules/mod_poectl.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/discovery/modules/mod_process.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/discovery/modules/mod_service.py

python -m autopep8 --recursive --in-place --select E701 ./

E701 multiple statements on one line (colon)

---

.pre-commit-config.yaml
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/basic_triggers/test_module1.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/sanity/test_switch_reload.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/test_utils/tb_utils.py
DentOS_Framework/DentOsTestbedDiscovery/src/dent_os_testbed/discovery/LocalRepository.py
DentOS_Framework/DentOsTestbedLib/gen/lib/md/mdlib.py
DentOS_Framework/DentOsTestbedLib/gen/lib/python/pylib.py

renamed l in line or link depending on case

E741 ambiguous variable name 'l'

---

.pre-commit-config.yaml
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/TestBed.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/connection/test_ssh.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/sanity/test_check_links.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/ConnectionHandlers/SerialHandler.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/FileHandlers/LocalFileHandler.py
DentOS_Framework/DentOsTestbedDiscovery/src/dent_os_testbed/discovery/Module.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/lldp/linux/linux_lldp_impl.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/onlp/linux/linux_onlp_sfp_info_impl.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/os/linux/linux_cpu_usage_impl.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/os/linux/linux_process_impl.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/poe/linux/linux_poectl_impl.py

E722 do not use bare 'except'

---

.pre-commit-config.yaml
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/test_utils/tb_utils.py
DentOS_Framework/DentOsTestbedLib/gen/plugins/doc/plugin.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/ethtool/ethtool.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/ethtool/linux/linux_ethtool_impl.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/onlp/linux/linux_onlp_sfp_info_impl.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/onlp/linux/linux_onlp_system_info_impl.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/os/linux/linux_cpu_usage_impl.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/os/linux/linux_memory_usage_impl.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/os/linux/linux_process_impl.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/poe_tester/dni/dni_poe_tester_impl.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/poe_tester/dni/poe_serial_handler.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/poe_tester/dni/poe_tester_client.py

set those offending string to raw
escape the escape char

W605 invalid escape sequence

---

DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/ethtool/linux/linux_ethtool_impl.py

`ethtool` does not support `show`/`set` commands, so remove the `command` argument.
Also, make sure that there is a space between cmd arguments.
Fixes: https://github.com/dentproject/testing/pull/282

Fix ethtool impl

---

.github/workflows/pre-commit-check.yml
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/stress/test_stress_disk.py

based on TWG meeting skipping the hanging test

skip the test while we have the hang bug

---

DentOS_Framework/DentOsTestbed/configuration/testbed_config/basic_infra1/testbed.json
DentOS_Framework/DentOsTestbed/configuration/testbed_config/basic_infra2/testbed.json

- Additional change related to https://github.com/dentproject/testing/issues/204
- Right now 33, 34, 35, 36 on infra 1 and 2 are connected to card 2vport 1 to 8 (added additional IXIA Ethernet card with support of 10/100/1000 speed half/full duplex )

Update basic_infra1, basic_infra2 testbed

---

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/L1/test_l1_port_state.py

- refactor **test_l1_port_state**::test_l1_link_up_state_software_power_cycle test
- add `import asyncio`

Refactor l1_port_state test

---

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/L1/test_l1_autodetect.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/vlan/test_vlan_default_configuration.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/vlan/test_vlan_increment_mac.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/vlan/test_vlan_priority.py

Adds wait required running tests without vpn

Update function param, add wait to tests

---

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/test_utils/cleanup_utils.py

Add `cleanup_kbyte_per_sec_rate_value(dev, all_values=False, bc=False, unk_uc=False, unreg_mc=False)` function for restore all or a specific  values changed during test.
**Values:** 
```
- bc_kbyte_per_sec_rate
- unk_uc_kbyte_per_sec_rate
- unreg_mc_kbyte_per_sec_rate values 
```
**For example(cleanup unreg_mc_kbyte_per_sec_rate values ):**
` await cleanup_kbyte_per_sec_rate_value(dent_dev, unreg_mc=True)`
All others similarly, however if you clear all the values ​​then:
` await cleanup_kbyte_per_sec_rate_value(dent_dev, all_values=True)`

Add cleanup_kbyte_per_sec_rate_value function

---

DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/ethtool/linux/linux_ethtool_impl.py

Fix parse_show method in Ethtool API

---

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/constants.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/storm_control/storm_control_utils.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/storm_control/test_storm_control_br_and_mc_lag_and_vlan_membership.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/storm_control/test_storm_control_br_and_unk_un_and_vlan_membership.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/storm_control/test_storm_control_broadcast_traffic.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/storm_control/test_storm_control_mc_lag_and_vlan_membership.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/storm_control/test_storm_control_rule_set_for_br_and_mc_traffic.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/storm_control/test_storm_control_rule_set_for_br_and_unk_uc_traffic.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/storm_control/test_storm_control_unk_un_lag_and_vlan_membership.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/storm_control/test_storm_control_unknown_unicast_traffic.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/storm_control/test_storm_control_unregistered_multicast_traffic.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/storm_control/test_storm_negative_known_unicast_traffic.py

**This includes:**
- test_storm_control_broadcast_traffic.py
- test_storm_control_unknown_unicast_traffic.py
- test_storm_negative_known_unicast_traffic.py
- test_storm_control_unregistered_multicast_traffic.py
- test_storm_control_rule_set_for_br_and_mc_traffic.py
- test_storm_control_rule_set_for_br_and_unk_uc_traffic.py
- test_storm_control_mc_lag_and_vlan_membership.py
- test_storm_control_unk_un_lag_and_vlan_membership.py
- test_storm_control_br_and_mc_lag_and_vlan_membership.py
- test_storm_control_br_and_unk_un_lag_and_vlan_membership.py
- storm_control_utils.py
- constants.py
- init.py

Add Storm Control tests

---

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv6/ipv6_utils.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv6/test_ipv6.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv6/test_ipv6_bridge.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv6/test_ipv6_ipv4.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv6/test_ipv6_nei.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv6/test_ipv6_route.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/test_utils/tb_utils.py

- test_ipv6_nei_ageing
- test_ipv6_route_metrics
- test_ipv6_nh_state

Add IPv6 route and neighbor tests

---

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_jumbo_frame.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv4/conftest.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv4/test_ipv4_mtu.py

- Add fixture `cleanup_mtu` to `test_bridging_jumbo_frame.py`
- Refactor `test_ipv4_oversized_mtu`

Add cleanup_mtu fixture and refactor

---

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/storm_control/storm_control_utils.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/storm_control/test_storm_control_different_rates.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/storm_control/test_storm_control_interaction_policer_rules.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/storm_control/test_storm_control_interaction_span_rule.py

**This includes:**
- test_storm_control_interaction_policer_rules.py
- test_storm_control_interaction_span_rule.py
- test_storm_control_different_rates.py
- storm_control_utils.py

Add storm_control tests

---

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/constants.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/policer/test_policer_basic_functionality.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/policer/test_policer_negative_add_rule_to_bond.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/policer/test_policer_rate_per_rule.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/policer/test_policer_rate_units.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/policer/test_policer_rules_priority.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/policer/test_policer_same_pref_rules_priority.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/test_utils/tc_flower_utils.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/ip/linux/linux_ip_link_impl.py

Add policer tests

---

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/test_utils/cleanup_utils.py

- Refactor `cleanup_kbyte_per_sec_rate_value` function
- Optimization of execution speed

Refactor cleanup_kbyte_per_sec_rate_value function

---

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/constants.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/devlink/conftest.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/devlink/devlink_utils.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/devlink/test_devlink_shared_block.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/devlink/test_devlink_single_block.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/test_utils/tc_flower_utils.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/tc/linux/linux_tc_filter_impl.py

Add Devlink functional test cases:
- test_devlink_basic[l4]
- test_devlink_basic[l2]
- test_devlink_basic[l3]
- test_devlink_rule_priority[shared_block]
- test_devlink_rule_priority[single_block]
- test_devlink_same_rule_pref[shared_block]
- test_devlink_same_rule_pref[single_block]
- test_devlink_random
- test_devlink_diff_rate_units[bit]
- test_devlink_diff_rate_units[kbit]
- test_devlink_diff_rate_units[gbit]
- test_devlink_diff_rate_units[bps]
- test_devlink_diff_rate_units[kbps]
- test_devlink_diff_rate_units[mbps]
- test_devlink_diff_rate_units[gbps]
- test_devlink_diff_rate_units[tbps]
- test_devlink_policer_log
Depends on: https://github.com/dentproject/testing/pull/316

Add Devlink functional tests

---

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/igmp/test_igmp_snooping.py

Add 1 IGMP functional test case:
- test_igmp_snooping_modified_query

Add 1 IGMP functional test

---

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/devlink/devlink_utils.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/devlink/test_devlink_sct.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/test_utils/tgen_utils.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/ixnetwork/ixnetwork_ixia_client_impl.py

Add 4 Devlink functions test cases:
- test_devlink_sct_basic_ports[1]
- test_devlink_sct_basic_ports[2]
- test_devlink_sct_basic_ports[4]
- test_devlink_static_trap_disable
Depends: #329

Add 4 Devlink functional tests

---

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/devlink/conftest.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/devlink/test_devlink_interact.py

- test_devlink_interact_acl_with_dyn_traps
- test_devlink_interact_dyn_traps_lag
- test_devlink_interact_static_traps_disabled
- test_devlink_interact_sct_lag

Add devlink interact tests

---

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/storm_control/storm_control_utils.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/storm_control/test_storm_control_packets.py

**This includes:**
- test_storm_control_packets.py
- storm_control_utils.py

Add StormControl test

---

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv6/test_ipv6_route.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/ixnetwork/ixnetwork_ixia_client_impl.py

Add IPv6 ICMP test

---

DentOS_Framework/DentOsTestbedLib/gen/model/dent/network/ip/link.yaml
DentOS_Framework/DentOsTestbedLib/gen/model/linux/network/ip/link.yaml
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/ip/linux/linux_ip_link_impl.py

Update` Ip link` api with `stp `commands

Add stp support to ip link api

---

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/constants.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/lacp/test_lacp_no_traffic.py

Adds 3 LACP tests:
```
- test_lacp_unsupported_modes
- test_lacp_max_ports_in_lags
- test_lacp_max_ports_in_lags
```

Add lacp no traffic tests

---

DentOS_Framework/DentOsTestbed/configuration/testbed_config/basic_agg1/testbed.json
DentOS_Framework/DentOsTestbed/configuration/testbed_config/basic_agg2/testbed.json
DentOS_Framework/DentOsTestbed/configuration/testbed_config/basic_dist1/testbed.json
DentOS_Framework/DentOsTestbed/configuration/testbed_config/basic_infra1/testbed.json
DentOS_Framework/DentOsTestbed/configuration/testbed_config/basic_infra2/testbed.json

Changes related to PR https://github.com/dentproject/testing/pull/345

Add loopback link to testbeds

---

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/constants.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ecmp/conftest.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ecmp/test_ecmp.py

Add Ecmp functional test cases:
- test_ecmp_nexthops_down[1]
- test_ecmp_nexthops_down[3]
- test_ecmp_hash_policy
- test_ecmp_traffic_distribution[basic]
- test_ecmp_traffic_distribution[nexthop_down]
- test_ecmp_traffic_distribution[dynamic]
- test_ecmp_distribution_lags

Add Ecmp functional tests

---

DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/ixnetwork/ixnetwork_ixia_client_impl.py

Resolves 2 point in the issue https://github.com/dentproject/testing/issues/308

Add check for traffic stoppage

---

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/stp/test_stp_convergence.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/stp/test_stp_loopback.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/stp/test_stp_ports.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/stp/test_stp_select_root.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/stp/test_stp_with_traffic.py

Add:
- test_stp_under_load[rstp]
- test_stp_under_load[stp]
- test_stp_convergence[rstp]
- test_stp_convergence[stp]

Add STP tests

---

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/lacp/test_lacp_blocked_port_stp_rstp.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/lacp/test_lacp_loopback_detection.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/lacp/test_lacp_root_bridge_stp_rstp.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/lacp/test_lacp_traffic_during_topology_convergence.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/ip/linux/linux_ip_link_impl.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/mstpctl/linux/linux_mstpctl_impl.py

Adds tests:
```
- test_lacp_root_port['rstp', 'stp']
- test_lacp_loopback_detection['rstp', 'stp']
- test_lacp_root_bridge_selection_stp['rstp', 'stp']
- test_lacp_traffic_during_topology_convergence['rstp', 'stp']
```
Add params to `IpLink `and `Mstpd `libs

Add lacp /stp interaction tests

---

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/stp/conftest.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/stp/stp_utils.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/stp/test_stp_config.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/stp/test_stp_rstp_config.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/bridge/linux/linux_bridge_link_impl.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/ixnetwork/ixnetwork_ixia_client_impl.py

- test_stp_hello_time[stp]
- test_stp_hello_time[rstp]
- test_stp_bpdu_guard
- test_stp_forward_delay
- test_stp_max_age
- test_stp_root_guard
Signed-off-by: Serhiy Boiko [serhiy.boiko@plvision.eu](mailto:serhiy.boiko@plvision.eu)

Add STP config tests

---

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/constants.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ifupdown2/conftest.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ifupdown2/ifupdown2_utils.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ifupdown2/test_ifupdown2.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ifupdown2/test_ifupdown_stp.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/vrrp/test_vrrp_ifupdown.py
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/vrrp/vrrp_utils.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/ip/linux/linux_ip_link_impl.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/ixnetwork/ixnetwork_ixia_client_impl.py

- test_ifupdown2_ipv4_ecmp
- test_ifupdown2_bridge
- test_ifupdown2_lacp
- test_ifupdown2_acl_random[single_block-acl_random]
- test_ifupdown2_acl_random[shared_block-acl_random]
- test_ifupdown2_acl_random[single_block-acl_and_trap_policer]
- test_ifupdown2_acl_random[shared_block-acl_and_trap_policer]
- test_ifupdown2_stp
- test_vrrp_ifupdown2

Add ifupdown2 tests

---

tools/USAGE.MD
tools/test_utils.py

Test analysis tool and documentation allows for easier interpretation and aggregation of test results.
Features include:
- view results sorted or grouped by subgroup (lacp, igmp, etc)
- export to csv and html table
- generate command to run only failed tests

Create test analysis utility

---

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/ConnectionHandlers/SSHHandler.py

- Previously, every SSH command would first do a call to 'date' to check that the connection was alive.
- Now, only do date call when a connection is first set up or if an SSH command times out and raises an exception.
Results: 
- Decreased "Date" command calls from 10000 to 1000 in functional (~90% Decrease) 
-  Decreased "Date" command calls from 40000 to 40 in dentv2 tests (~99% Decrease)

Reduce Extraneous SSH Date Calls
