MAINTAINERS.md
MAINTAINERS.md describes the main contributors to
the testcases project.
Signed-off-by: Jessica Wagantall <jwagantall@linuxfoundation.org>
=> Fix: Add MAINTAINERS.md file

DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/ip/linux/linux_ip_neighbor_impl.py
This will allow to use the `parse_output=True` argument with the `IpNeighbor` class. Example:
```python
out = await IpNeighbor.show(input_data=[{dent: [{"cmd_options": "-j"}]}], parse_output=True)
print(out[0][dent]["parsed_output"])  # [ ... ]
```
=> Add output parser to IpNeighborImpl

DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/ixnetwork/ixnetwork_ixia_client_impl.py
When setuping streams set the `bi_directional` flag to enable bi-directional traffic flow:
```python
streams = {
"traffic": {
"type": "ipv4",
"bi_directional": True,
...
},
}
await tgen_utils_setup_streams(tgen_dev, config_file_name, streams)
```
=> Add ability to configure bi-directional traffic

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/test_utils/tgen_utils.py
Move `TrafficGen.connect()` to a separate function, so it can be reused, and remove duplicate code.
Introduce a new helper function that is used to create a device group config which can be used in `TrafficGen.connect()`.
Example usage:
```python
dev_groups = tgen_utils_dev_groups_from_config([
{"ixp": tg_port[0], "ip": "192.168.1.2", "gw": "192.168.1.1", "plen": 24},
{"ixp": tg_port[1], "ip": "192.168.2.2", "gw": "192.168.2.1", "plen": 24},
])
await tgen_utils_traffic_generator_connect(tgen_dev, tgen_ports, swp_ports, dev_groups)
```
Resolves: https://github.com/dentproject/testing/issues/63
=> Make endpoint creation independent of device configuration

DentOS_Framework/DentOsTestbed/Requirements.txt
pexpectasyncio does not exist in pypi removing for now as it is not used anywhere
=> remove pexpectasyncio

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/conftest.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/test_utils/cleanup_utils.py
Added pytest fixtures that can be used to clean up device after the test:
* remove bridges
* remove qdiscs
* remove VRFs
* flush IP addresses
* remove created routes
* close Ixia session
=> Add cleanup functionality

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/constants.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv4/conftest.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv4/test_ipv4_addr.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv4/test_ipv4_class_x_discarded.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv4/test_ipv4_en_dis_fwd.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv4/test_ipv4_routing.py
Update pytest suite groups.
Use cleanup fixtures instead of try-catch-finally.
Add a fixture to automatically enable ipv4 forwarding.
Use `*_` syntax for argument unpacking in list comprehensions.
Move @pytest.mark decorators to top of test file.
Update random routing test.
Fix route_between_vlan_devs test.
Fix get_random_ip function.
=> Update IPv4 tests

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/test_utils/tgen_utils.py, DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/ixnetwork/ixnetwork_ixia_client_impl.py
Update `IxnetworkIxiaClientImpl` class to accept new types of field values when creating streams.
When creating streams instead of specifying a string you can specify a dict that will describe what values you want the field to have:
```python
streams = {
"stream_name": {
"type": "raw",
"srcMac": "02:00:00:00:00:01",
"dstMac": {"type": "random"},
}
}
await tgen_utils_setup_streams(tgen_dev, None, streams)
```
Fields that support this feature:
- dstMac
- srcMac
- vlanID
- dstIp
- srcIp
- dstPort
- srcPort
- icmpType
- icmpCode
Supported field types:
- single (default value, used when a string is passed instead of a dict)
- increment
- decrement
- list
- random
More examples:
```python
streams = {
"stream_name": {
"type": "raw",
"srcIp": {"type": "single",
"value": "192.168.1.1"},
"srcIp": …
```
=> Add ability to send increment traffic

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/vlan/test_vlan_all_supported_modes.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/test_utils/br_utils.py
Adds following tests:
```
test_all_supported_modes_unicast
test_all_supported_modes_multicast
test_all_supported_modes_broadcast
```
Signed-off-by: Stepan Vovk <stepan.vovk@plvision.eu>
=> Add all supported modes VLAN tests

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/test_utils/tgen_utils.py
When sending "raw" traffic type the "Source/Dest Value Pair" field is not present, which causes a "KeyError" exception.
=> Make "Source/Dest Value Pair" optional in get_traffic_stats

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/test_utils/tgen_utils.py, DentOS_Framework/DentOsTestbedLib/gen/model/dent/traffic/traffic.yaml, DentOS_Framework/DentOsTestbedLib/gen/model/traffic/ixia/ixia.yaml, DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/discovery/ReportSchema.py, DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/ixnetwork/ixnetwork_ixia_client.py, DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/ixnetwork/ixnetwork_ixia_client_impl.py, DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/traffic_gen.py
Update `traffic` and `ixia` yaml models.
Add two new APIs:
- TrafficGen.send_ping()
- TrafficGen.send_arp()
`send_ping()` accepts a list of tg_ports, destination ip, and optional source ip (in case that the port has multiple endpoints).
`send_arp()` accepts a list of tg_ports and optional source ip.
Usage:
```python
out = await TrafficGen.send_arp(input_data=[{tgen_dev.host_name: [
{"port": tg_ports[0]},
{"port": tg_ports[1], "src_ip": "2.2.2.2"},
]}])
assert out[0][tgen_dev.host_name]["rc"] == 0
out = await TrafficGen.send_ping(input_data=[{tgen_dev.host_name: [
{"port": tg_ports[0], "dst_ip": "1.1.1.1"},
{"port": tg_ports[1], "dst_ip": "2.2.2.1", "src_ip": "2.2.2.2"},
]}])
assert out[0][tgen_dev.host_name]["rc"] == 0
status = await tgen_utils_send_ping(
tgen_dev,
[{"ixp": tg_ports[0], …
```
=> Add send_ping/send_arp interface for Ixia traffic gen

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv4/conftest.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv4/test_ipv4_addr.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv4/test_ipv4_class_x_discarded.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv4/test_ipv4_en_dis_fwd.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv4/test_ipv4_routing.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/test_utils/tgen_utils.py
Remove autouse from ipv4 fixture.
Add missing f to f-string in assert.
=> Fix IPv4 fixture and fix assert message

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/cli.py
dentos_runtest_testbed won't be failing if unknown arguments is provided. All unrecognized arguments will be passed to the pytest as is.
=> Allow passing CLI arguments to pytest.

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv4/conftest.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv4/test_ipv4_mtu.py
- test_ipv4_oversized_mtu
- test_ipv4_fragmentation
=> Add IPv4 mtu tests

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_admin_state_down_up.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_ageing.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_backward_forwarding.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_fdb_flush_on_down.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_jumbo_frame.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_learning_address.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_learning_illegal_address.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_mac_table_size.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_packets_oversize.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_packets_undersize.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_remove_restore_from_vlan.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_static_entries.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_traffic_from_nomaster.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_wrong_fcs.py
Update all Bridging tests.
- Used cleanup fixtures between tests
- Fixed typo errors
- Fixed call print
- Fixed f-strings
- Removed unnecessary spaces
- Corrected grammatical errors
=> Update Bridging tests

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/test_utils/tgen_utils.py, DentOS_Framework/DentOsTestbedLib/gen/model/dent/traffic/traffic.yaml, DentOS_Framework/DentOsTestbedLib/gen/model/traffic/ixia/ixia.yaml, DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/ixnetwork/ixnetwork_ixia_client.py, DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/ixnetwork/ixnetwork_ixia_client_impl.py, DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/traffic_gen.py
Added functionality which can clear traffic items.
- **Example:**
`await tgen_utils_clear_traffic_items(tgen_dev)`
- **Modified files:**
DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/test_utils/tgen_utils.py
DentOS_Framework/DentOsTestbedLib/gen/model/dent/traffic/traffic.yaml
DentOS_Framework/DentOsTestbedLib/gen/model/traffic/ixia/ixia.yaml
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/ixnetwork/ixnetwork_ixia_client.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/ixnetwork/ixnetwork_ixia_client_impl.py
DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/traffic_gen.py
Resolves: #125
=> add functionality which clear traffic items

DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/ixnetwork/ixnetwork_ixia_client_impl.py
The console log was printing "Changing port: {} media mode from copper to fiber" even when the real direction was from fiber to copper.
=> Fixed log message about selected media type for IxNetwork.

DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/ixnetwork/ixnetwork_ixia_client_impl.py
Add support for dscp (upper 6 bits) and ecn (lower 2 bits) in traffic items.
Add DSCP tracking.
```python
streams = {
"ipv4 with dscp 0..63 ecn 0": {
"type": "ipv4",
"dscp_ecn": {"type": "increment",
"start": 0,
"step": 1<<2,
"count": 64},
},
}
await tgen_utils_setup_streams(tgen_dev, None, streams)
```
=> Add ability to specify DSCP in streams

DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/tc/linux/linux_tc_qdisc_impl.py
`bands`, `strict`, `quanta`, and `priomap` are required for `ets` qdisc.
`rate`, `burst`, and `limit` are required for `tbf`/`red` qdiscs.
Add ability to specify `parent` and `root` when creating qdiscs.
Add filter options for `show` command
=> Add new field to TcQdisc class

DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/ixnetwork/ixnetwork_ixia_client_impl.py
Added code to reuse Ixia Traffic Gen Session, if session already exists use it else create new session.
This PR will address the Session initialization Portion of https://github.com/dentproject/testing/issues/155
=> Added code to reuse Ixia Traffic Gen Session

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/test_utils/tgen_utils.py, DentOS_Framework/DentOsTestbedLib/gen/model/dent/traffic/traffic.yaml, DentOS_Framework/DentOsTestbedLib/gen/model/traffic/ixia/ixia.yaml, DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/ixnetwork/ixnetwork_ixia_client.py, DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/ixnetwork/ixnetwork_ixia_client_impl.py, DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/traffic_gen.py
Add ability to get egress stats by enabling egress tracking.
Currently supported tracking fields:
- `vlan` - vlan id 0..15
- `vlan_4k` - vlan id 0..4095
- `pcp` - vlan priority 0..7
- `dscp` - ipv4 dscp (precedence + tos) 0..63
Usage:
```python
streams = {
"stream with egress tracking": {
"type": "ethernet",
"vlanID": 10,
"egress_track_by": ["vlan", "pcp"],
},
}
await tgen_utils_setup_streams(tgen_dev, None, streams)
await tgen_utils_start_traffic(tgen_dev)
await asyncio.sleep(traffic_duration)
await tgen_utils_stop_traffic(tgen_dev)
stats = await tgen_utils_get_traffic_stats(tgen_dev, "Traffic Item Statistics")
for row in stats.Rows:
egress_stats = await tgen_utils_get_egress_stats(tgen_dev, row)
for e_row in egress_stats:
if e_row["Traffic Item"]:  # first row
tx = int(e_row["Tx …
```
=> Add Egress tracking

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/basic_triggers/test_clean_config.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/sanity/test_restart_networking.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/test_utils/sanity_utils.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/test_utils/tb_utils.py
=>  remove amazon specific names and code

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/basic_triggers/test_interfaces_relaod.py
in to order to fix issue 108
- get the original interfaces file then
- copy to the new file to be written
- open the file new file in append mode and all the link down commands
=> get the original interfaces file and then append the link down commands

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/basic_triggers/test_interfaces_relaod.py
had a typo in using the file name. fixed the bug.
=> fix the file name order for copying

DentOS_Framework/DentOsTestbed/configuration/testbed_config/sit/agg1/QUAGGA_CONFIG, DentOS_Framework/DentOsTestbed/configuration/testbed_config/sit/agg2/QUAGGA_CONFIG, DentOS_Framework/DentOsTestbed/configuration/testbed_config/sit/dist1/QUAGGA_CONFIG, DentOS_Framework/DentOsTestbed/configuration/testbed_config/sit/infra1/QUAGGA_CONFIG, DentOS_Framework/DentOsTestbed/configuration/testbed_config/sit/infra2/QUAGGA_CONFIG
QUAGGA_CONFIG there is no policy (route-map) defined for peer-group IXIA. 
Due to that it is not able to receive routes In/Out. 
If we add “no bgp ebgp-requires-policy”, it advertises and receives the routes from other peers and traffic flows fine.
=> QUAGGA_CONFIG update

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/constants.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/acl/test_acl.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/acl/test_acl_all_selectors.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/acl/test_acl_negative.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/test_utils/tc_flower_utils.py, DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/tc/linux/linux_tc_filter_impl.py
Update suite groups.
Update tcutil_tc_rules_to_tgen_streams function.
Update LinuxTcFilterImpl class.
Add helper functions.
Tests:
- test_acl_all_selectors
- test_acl_addition_deletion_under_traffic
- test_acl_rule_deletion
- test_acl_rule_without_qdisk
- test_acl_skip_sw_hw_selector
=> Add ACL tests

DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/ixnetwork/ixnetwork_ixia_client_impl.py
`if not "type" in` is equivalent to `if False in`, so use `if "type" not in` to check if "type" key is in the dict.
Use str for values instead of passing them directly.
Get values directly from dict instead of using `.get()` where values are mandatory.
=> Fix parse_multivalue

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/test_utils/tgen_utils.py, DentOS_Framework/DentOsTestbedLib/gen/model/dent/traffic/traffic.yaml, DentOS_Framework/DentOsTestbedLib/gen/model/traffic/ixia/ixia.yaml, DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/ixnetwork/ixnetwork_ixia_client.py, DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/ixnetwork/ixnetwork_ixia_client_impl.py, DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/traffic_gen.py
Add ability to assign IPv6 to Ixia ports.
Add ability to create IPv6 traffic.
Add SendNs function.
Update set_traffic function:
- instead of using 2 functions with duplicate code to create traffic there is only 1 now.
- the user can specify `type: ipv6` to create IPv6 traffic.
- the user can also specify `type: ethernet | raw` and `protocol: ipv6` to create ethernet/raw traffic with IPv6 header.
- old behavior is preserved.
Resolves: https://github.com/dentproject/testing/issues/139
=> Add IPv6 support

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/dentv2/acl/scale/test_acl_scale_max_rules.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/dentv2/acl/scale/test_acl_scale_max_rules_store.py
After the introduction of a commit (1d4dc99) that allowed to create traffic items with increment value fields the behavior for specifying src/dst ports has changed.
The port should only be specified as a single value string, or as a dict with a type (increment/decrement/random/list) and type parameters.
No issue is associated with this fix.
=> Fix ACL Scale tests

DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/bridge/linux/linux_bridge_link_impl.py, DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/bridge/linux/linux_bridge_mdb_impl.py, DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/ip/linux/linux_ip_link_impl.py
Updated `linux_bridge_link_impl.py`, added missing parameter: `fastleave`.
Updated `linux_bridge_mdb_impl.py`, added missing parametrs: `device, port, group, vid` and function to `parse_output`.
Updated `linux_ip_link_impl.py`, added missing parametrs: `mcast_snooping, mcast_igmp_version, mcast_querier, mcast_querier_interval.`
Resolves: #226
=> Update bridge_link_impl, bridge_mdb_impl, ip_link_impl

.pre-commit-config.yaml, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/alpha/switching/test_trunk_port.py, DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/ixnetwork/ixnetwork_ixia_client_impl.py
- DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/alpha/switching/test_trunk_port.py:10:1: F811 redefinition of unused 'tgen_utils_get_loss' from line 10
- DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/ixnetwork/ixnetwork_ixia_client_impl.py:9:1: F811 redefinition of unused 'Files' from line 7
=>  F811 redefinition of unused

.pre-commit-config.yaml, DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/ethtool/linux/linux_ethtool_impl.py
add another {} into the format line, this change looks prone to collaterals, while previous code was wrong it may have worked fine that way
=> F523 '...'.format(...) has unused arguments at position(s): 1

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/conftest.py
Pytest fails with an error:
```
E   pluggy._manager.PluginValidationError: Plugin '/usr/local/lib/python3.10/dist-packages/dent_os_testbed/test/conftest.py' for hook 'pytest_runtest_makereport'
E   hookimpl definition: pytest_runtest_makereport(item, call)
E   Declared as hookwrapper=True but function is not a generator function
```
`@pytest.hookimpl` expects `pytest_runtest_makereport` to be a generator, so restore the previous behavior by adding yield to the function.
Fixes: https://github.com/dentproject/testing/pull/294
=> Fix pytest_runtest_makereport hook

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv4/conftest.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv6/ipv6_utils.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv6/test_ipv6.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv6/test_ipv6_bridge.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv6/test_ipv6_ipv4.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv6/test_ipv6_route.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/test_utils/cleanup_utils.py
- test_ipv64_nh_reconfig
- test_ipv64_nh_routes
- test_ipv6_route_default_offload
- test_ipv6_route_lpm
Update cleanup_ip_addrs to support IPv6.
Remove ping/NS from previous IPv6 tests, since it is no longer required.
Update remove_default_gateway fixture to support IPv6.
Update IPv6 utils functions.
=> Add IPv6/IPv4 and IPv6 route tests

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/conftest.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/test_utils/cleanup_utils.py
Add `cleanup_bonds(dev)` function for remove all bonds created during test.
**For example:**
` await cleanup_bonds(dent_dev)`
=> Add cleanup_bonds function

DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/ip/linux/linux_ip_link_impl.py, DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/ip/linux/linux_ip_route_impl.py
**Update linux_ip_route_impl.py**
✓ Add parameter `dev` to `format_show` function
**Update linux_ip_link_impl.py**
✓ Add parameter `vlan_default_pvid` to `format_set` function
=> Add parameters to IpLink and IpRoute APIs

.pre-commit-config.yaml, DentOS_Framework/DentOsTestbedLib/gen/plugins/test/plugin.py
fixes the name of the variable used in the PyMethod
=> F841 local variable 'parse_cmd_body' is assigned to but never used

DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/ethtool/linux/linux_ethtool_impl.py
Adds missing link modes.
Enables parsing to 
```
'link_partner_advertised_link_modes': '10baseT/Half 10baseT/Full ' 
'100baseT/Half 100baseT/Full ' 
'1000baseT/Full',
```
Instead of 
` 'link_partner_advertised_link_modes': '10baseT/Half 10baseT/Full '`
=> Fix ethtool show for link partner mode

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_packets.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/test_utils/tb_utils.py
- Add a function `async def get_port_stats(device_host_name, ports)` to `dent_os_testbed/utils/test_utils/tb_utils.py`
- Add `import get_port_stats` to `test_bridging_packets.py`
=> Add get_port_stats and refactor

DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/ixnetwork/ixnetwork_ixia_client_impl.py
Added ability to set `etherType` for traffic items, by default `etherType` is **autoconfigured based on upper layer**.
=> Add support to set etherType

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/conftest.py
Changed the TG cleanup function to stop the traffic instead of stopping all the protocols (will improve test run speed).
=> Refactor cleanup_tgen function

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/L1/test_l1_autodetect.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/L1/test_l1_autoneg.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/L1/test_l1_config.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/L1/test_l1_forced_speed.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/L1/test_l1_mixed_speed.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/test_utils/tb_utils.py
Several L1 tests can not be run on devices depending on ports' supported link speeds. Added the mechanism to skip the test if it does not match the device requirements.
=> Skip L1 tests on unsupported device

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv6/ipv6_utils.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv6/test_ipv6.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv6/test_ipv6_bridge.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv6/test_ipv6_ipv4.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv6/test_ipv6_nei.py
Add new tests:
- test_ipv6_flags
- test_ipv6_secondary_addr
- test_ipv6_nei_change
Fix the previous test:
- test_ipv6_nei_ageing
Make utils functions more generic:
- verify_dut_addrs
- verify_dut_neighbors
- wait_for_nei_state
=> Add IPv6 tests

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/constants.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/conftest.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ecmp/conftest.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ecmp/test_ecmp.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv4/conftest.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/vrrp/conftest.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/vrrp/test_vrrp_basic.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/vrrp/test_vrrp_priority.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/vrrp/vrrp_utils.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/test_utils/cleanup_utils.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/test_utils/tb_utils.py
- test_vrrp_basic_on[bridge]
- test_vrrp_basic_on[port]
- test_vrrp_priority_on[bridge]
- test_vrrp_priority_on[port]
- test_vrrp_basic_down_on[bridge]
- test_vrrp_basic_down_on[port]
Also, updated cleanup functions, since they should not care whether DUTs have any links to TG.
=> Add VRRP tests

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/conftest.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/lacp/test_lacp_distribution_over_ecmp.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/lacp/test_lacp_negative_acl_over_lag.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/lacp/test_lacp_routing_over_bridge.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/lacp/test_lacp_routing_over_lacp.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/lacp/test_lacp_routing_over_vlan_device.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/lacp/test_lacp_routing_over_vrf.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/lacp/test_lacp_routing_over_vrf_and_vlan_device.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/lacp/test_lacp_with_all_vlan_modes.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/test_utils/cleanup_utils.py, DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/ip/linux/linux_ip_link_impl.py, DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/ip/linux/linux_ip_route_impl.py
1. Add LACP tests:
- test_lacp_unsupported_modes
- test_lacp_max_lags
- test_lacp_max_ports_in_lags
- test_lacp_ecmp_distribution_over_lag
- test_lacp_acl_negative
- test_lacp_routing_over_bridge
- test_lacp_routing_over_lacp
- test_lacp_routing_over_vlan_device
- test_lacp_routing_over_lag_vrf
- test_lacp_routing_over_lag_vrf_vlan_device
- test_lacp_all_vlan_modes
2. Adds vrf table cleanup fixture
=> Add lacp tests with traffics, fix cleanup and tgen utils

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/devlink/conftest.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/devlink/devlink_utils.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/vrrp/conftest.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/vrrp/test_vrrp_advert.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/vrrp/test_vrrp_basic.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/vrrp/test_vrrp_interact.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/vrrp/test_vrrp_preempt.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/vrrp/test_vrrp_priority.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/vrrp/test_vrrp_under_traffic.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/vrrp/test_vrrp_vrouter.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/vrrp/vrrp_utils.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/test_utils/tgen_utils.py
Add a generic polling function.
Update devlink define_bash_utils fixture.
New tests:
- test_vrrp_and_stp
- test_vrrp_preempt_on[bridge]
- test_vrrp_preempt_on[port]
- test_vrrp_under_traffic[bridge]
- test_vrrp_under_traffic[port]
- test_vrrp_under_traffic[vlan]
- test_vrrp_multiple_addr
- test_vrrp_max_instances
- test_vrrp_master_and_backup
- test_vrrp_advert_overflow
- test_vrrp_and_acl
Update setup_topo_for_vrrp function, which will allow to use:
- TG - DUT links
- links between infra devices
- VRRP over bridge or port or bridge vlan interfaces
Update verify_vrrp_ping function:
- Count only icmp reply packets.
- Pass interval as an argument.
- Add an argument to run tcpdump without running ping.
Signed-off-by: Serhiy Boiko [serhiy.boiko@plvision.eu](mailto:serhiy.boiko@plvision.eu)
=> Add VRRP tests with traffic

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/constants.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/lldp/conftest.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/lldp/lldp_utils.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/lldp/test_lldp_receive.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/lldp/test_lldp_transmit.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/lldp/test_lldp_tx_rx.py
Add Lldp functional tests:
- test_lldp_received[basic]
- test_lldp_received[mandatory]
- test_lldp_received[optional]
- test_lldp_received[ttl]
- test_lldp_rx[disable]
- test_lldp_rx[port_down_up]
- test_lldp_transmitted[basic]
- test_lldp_transmitted[mandatory]
- test_lldp_transmitted[optional]
- test_lldp_tx[disabled]
- test_lldp_tx[port_down]
- test_lldp_tx[interval]
- test_lldp_tx_hold
- test_lldp_bridge
- test_lldp_enable_disable_ports
- test_lldp_lag
- test_lldp_max_neighbours
Depends on: #360
=> Add Lldp functional tests

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/basic_triggers/test_module1.py
Spelling Bug fixed in test: basic_triggers  -> test_module1 -> test_link_up_down
basic_triggers: test_link_up_down: Use correct variable link to assign link name
=> Fix Spelling Bug collateral from previous fix rename l to link

DentOS_Framework/DentOsTestbed/.gitignore, DentOS_Framework/DentOsTestbed/configuration/testbed_config/basic_infra1/testbed_vm.json, DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/ixnetwork/ixnetwork_ixia_client_impl.py
- Workaround to skip hardware configuration of non-hardware load modules in IxNetwork Client Implementation
- Created and tested VM testbed configuration using the infra layout
- 138 Tests passing, with ongoing development to reach parity with hardware
<table style="width:100%"><tr><th>Test Suite Name</th><th>Ran</th><th>Passed</th> <th>Failed</th><th>Skipped</th><th>Time</th></tr>
<tr><td>alpha_lab_testing</td><td>32</td><td>31</td> <td>1</td><td>0</td><td>2068.706</td></tr>
<tr><td colspan="6"><details><summary>&emsp;Results
</summary>
<table>
<tr><th>Test Name</th><th>Status</th><th>Message</th></tr>
<tr><td>test_alpha_lab_static_routing_kernel_route_on_table</td><td>failure</td><td>ValueError: invalid literal for int() with base 10...</td></tr> …
=> Add VM Support for IxNetwork Client Interaction, VM Testbed Configuration

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/ConnectionHandlers/SSHHandler.py
Passing an empty input to an API class causes the test to hang with a message `Interactive shell requested`. This state is recoverable only if the user forcefully stops the test (and as a consequence all subsequent tests). There is no timeout and the test might be hanging indefinitely.
Since we will not get any output from the connection there is no point in continuing the test execution and it is safe to raise an exception and fail the test.
This behavior is most likely to be seen in tests that fetch some data from the DUT and try to act on that data. For example the test will fetch DUT neighbors (which the DUT might or might not have) and try to remove specific entries.
```python
await IpNeighbor.show(input_data=[{dent: [{'cmd_options': '-j'}]}])  # [ ... ]
await …
```
=> Fix `Interactive shell requested`

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/alpha/static_routing/test_kernel_route.py
- `static_routing: kernel_route_on_table:` generate valid int from net device string
`swp` is declared as `'ma1'`, which has 3 characters, so `swp[3:]` is empty.
```
>       sip = '.'.join(swp_info['ip'][:-1] + [str(int(swp[3:]) * 2)])
E       ValueError: invalid literal for int() with base 10: ''
```
```
Passed | alpha/static_routing/test_kernel_route.py::test_alpha_lab_static_routing_kernel_route_on_table | 230.71
```
=> Fix IP String Formatting in static_routing: kernel_route_on_table

DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/ixnetwork/ixnetwork_ixia_client_impl.py
- Enable Promiscuous Mode on VM Ports
- Use consistent floating Auto-Instrumentation mode 
<table style="width:100%"><tr><th>Test Suite Name</th><th>Ran</th><th>Passed</th> <th>Failed</th><th>Errors</th><th>Skipped</th><th>Time</th></tr>
<tr><td>alpha_lab_testing</td><td>32</td><td>32</td> <td>0</td><td>0</td><td>0</td><td>2300.395</td></tr>
<tr><td colspan="6"><details><summary>&emsp;Results
</summary>
<table>
<tr><th>Test Name</th><th>Status</th><th>Message</th></tr>
<tr><td>test_alpha_lab_bgp_routing_as_path_filtering</td><td>pass</td><td></td></tr>
<tr><td>test_alpha_lab_bgp_routing_communities</td><td>pass</td><td></td></tr>
<tr><td>test_alpha_lab_bgp_routing_local_pref</td><td>pass</td><td></td></tr>
<tr><td>test_alpha_lab_bgp_routing_med_metric</td><td>pass</td><td></td></tr> …
=> Fix VM Port IxNet Configuration 

DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/ixnetwork/ixnetwork_ixia_client_impl.py
- Replaced individual port additions with Batch Addition to prevent ports restarting one at a time
- Replaced constant sleep with a StatViewAsssitant protocol check
- Measured ~15% speedup in test runtime
=> Optimize Ixnet VPort Addition, Protocol Startup Timing

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/lacp/test_lacp_routing_over_bridge.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/lacp/test_lacp_routing_over_lacp.py, DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/lacp/test_lacp_routing_over_vlan_device.py
If loss percentage is tested while traffic is ongoing, there is a possibility of packets that are still in route not being counted, leading to unnecessary test failure. Solution is to stop traffic before checking loss percentage.
=> Stop traffic before testing loss percentage

DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/dentv2/acl/perf/test_acl_perf_load.py
- Previously, `test_dentv2_acl_perf_load_chains` would run till exhaustion and test that the time was less than 166 seconds. 
- Now, it will only run up to 166 seconds (test stops when limit is reached)
- Prevents hangs / overly long runs
=> Stop test on dentv2 chain timeout

DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/ixnetwork/ixnetwork_ixia_client_impl.py
* Optimize using BatchAdd for Endpoints
* Remove redundant TrafficItem list
* Wrap traffic generate into single call
* Only send ARPs when protocols are down
=> Optimize IxNet Endpoints using BatchAdd, Traffic Generate

DentOS_Framework/DentOsTestbed/configuration/testbed_config/basic_agg1/testbed.json, DentOS_Framework/DentOsTestbed/configuration/testbed_config/basic_agg2/testbed.json, DentOS_Framework/DentOsTestbed/configuration/testbed_config/basic_dist1/testbed.json, DentOS_Framework/DentOsTestbed/configuration/testbed_config/basic_infra1/testbed.json, DentOS_Framework/DentOsTestbed/configuration/testbed_config/basic_infra2/testbed.json, DentOS_Framework/DentOsTestbed/configuration/testbed_config/sit/agg1/NETWORK_INTERFACES, DentOS_Framework/DentOsTestbed/configuration/testbed_config/sit/dist1/NETWORK_INTERFACES, DentOS_Framework/DentOsTestbed/configuration/testbed_config/sit/infra2/NETWORK_INTERFACES, DentOS_Framework/DentOsTestbed/configuration/testbed_config/sit/testbed.json
Fixed all testbeds friendlyName to be consistent with sit testbed. Grouped testbeds with serial console and pdu devices
=> Update testbed configs
